# Generated by Django 5.1.7 on 2025-03-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=128, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
