# Generated by Django 5.1.7 on 2025-03-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacations',
            new_name='Vacation',
        ),
    ]
