# Generated by Django 5.1.7 on 2025-04-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_vacations_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=128, verbose_name='Название объявления')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
