# Generated by Django 5.1.7 on 2025-04-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_advertisment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisment',
            new_name='Advertisement',
        ),
    ]
