# Generated by Django 5.1.7 on 2025-04-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firtsname',
            new_name='firstname',
        ),
    ]
