# Generated by Django 5.1.7 on 2025-04-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_firtsname_user_firstname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
