# Generated by Django 5.1.7 on 2025-04-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.IntegerField()),
                ('title', models.CharField(max_length=128, verbose_name='Название объявления')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.IntegerField()),
                ('title', models.CharField(max_length=128, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
