# Generated by Django 5.1.7 on 2025-04-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='username',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='salary',
            field=models.IntegerField(default=9999, verbose_name='Заработная плата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
