# Generated by Django 5.1.7 on 2025-04-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_advertisement_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
    ]
