# Generated by Django 5.1.7 on 2025-04-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favoriteadvertisement_favoritevacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='count_views',
            field=models.BigIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='count_views',
            field=models.BigIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
